apiVersion: v1
kind: Pod
metadata:
  name: my-try3
  labels:
    env: prod
    app: main
    tier: front
spec:
  containers:
    - name: cont-web
      image: nginx:latest
      ports:
        - containerPort: 80

    - name: container-api
      image: tomcat:latest
      ports:
        - containerPort: 8080